server:
  port: 9088

spring:
  application:
    name: auth-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus